/*
 * File: app/view/TicketFormWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TicketTracker.view.TicketFormWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.ticketFormWindow',

    requires: [
        'TicketTracker.view.TicketForm'
    ],

    height: 300,
    width: 500,
    closeAction: 'hide',
    title: 'Edit Ticket',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            buttons: [
                {
                    text: 'Save',
                    action: 'saveTicket'
                }
            ],
            items: [
                {
                    xtype: 'ticketForm'
                }
            ]
        });

        me.callParent(arguments);
    }

});